# Generated by Django 5.0.6 on 2024-06-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_profile',
            fields=[
                ('customer_name', models.TextField(primary_key=True, serialize=False)),
                ('customer_address', models.TextField()),
                ('contact_person', models.TextField(blank=True)),
                ('phone_number', models.TextField(null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='supplier_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.TextField()),
                ('supplier_address', models.TextField()),
                ('contact_person', models.TextField(blank=True)),
                ('phone_number', models.CharField(null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
