# Generated by Django 5.0.6 on 2024-06-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_supplier_profile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cosmic_order',
            fields=[
                ('order_no', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('freight', models.TextField(blank=True, null=True)),
                ('freight_price', models.FloatField(blank=True, null=True)),
                ('payment_type', models.TextField(blank=True, null=True)),
                ('measurement_type', models.TextField(blank=True, null=True)),
                ('transportation', models.TextField(blank=True, null=True)),
                ('shipment_type', models.TextField(blank=True, null=True)),
                ('approved_by', models.TextField(blank=True, null=True)),
                ('PR_before_vat', models.FloatField(blank=True, null=True)),
                ('status', models.TextField(blank=True, default='Pending', null=True)),
                ('ref_no', models.TextField(null=True)),
                ('total_quantity', models.FloatField(blank=True, null=True)),
                ('remaining', models.FloatField(blank=True, null=True)),
                ('port_of_loading', models.TextField(null=True)),
                ('port_of_discharge', models.TextField(blank=True, null=True)),
                ('final_destination', models.TextField(blank=True, null=True)),
                ('country_of_origin', models.TextField(null=True)),
                ('consignee', models.ForeignKey(blank=True, db_column='consignee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='users.customer_profile')),
                ('customer_name', models.ForeignKey(db_column='customer_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_to_customer', to='users.customer_profile')),
                ('notify_party', models.ForeignKey(blank=True, db_column='notify_party', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_party_one', to='users.customer_profile')),
                ('notify_party2', models.ForeignKey(blank=True, db_column='notify_party2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_to_bank', to='users.customer_profile')),
                ('supplier_name', models.ForeignKey(db_column='supplier_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_to_supplier', to='users.supplier_profile')),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id_numeric', models.AutoField(primary_key=True, serialize=False)),
                ('hs_code', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('before_vat', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('measurement', models.TextField(blank=True, null=True)),
                ('order_no', models.ForeignKey(blank=True, db_column='order_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.cosmic_order')),
            ],
        ),
    ]
