# Generated by Django 5.0.6 on 2024-06-24 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_codes',
            fields=[
                ('hs_code', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('new_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
